/**
 * Q-Mak UI/UX Update Script
 * This script helps update all icons and colors across the entire system
 */

// Icon mapping from Font Awesome to Bootstrap Icons
const iconMapping = {
    // Common icons
    'fas fa-bell': 'bi bi-bell-fill',
    'far fa-bell': 'bi bi-bell',
    'fas fa-eye': 'bi bi-eye-fill',
    'far fa-eye': 'bi bi-eye',
    'fas fa-edit': 'bi bi-pencil-square',
    'fas fa-trash': 'bi bi-trash-fill',
    'fas fa-times': 'bi bi-x-lg',
    'fas fa-check': 'bi bi-check-lg',
    'fas fa-check-circle': 'bi bi-check-circle-fill',
    'fas fa-times-circle': 'bi bi-x-circle-fill',
    'fas fa-info-circle': 'bi bi-info-circle-fill',
    'fas fa-exclamation-triangle': 'bi bi-exclamation-triangle-fill',
    'fas fa-plus': 'bi bi-plus-lg',
    'fas fa-minus': 'bi bi-dash-lg',
    'fas fa-search': 'bi bi-search',
    'fas fa-filter': 'bi bi-funnel-fill',
    'fas fa-download': 'bi bi-download',
    'fas fa-upload': 'bi bi-upload',
    'fas fa-save': 'bi bi-save',
    'fas fa-print': 'bi bi-printer-fill',
    'fas fa-cog': 'bi bi-gear-fill',
    'fas fa-cogs': 'bi bi-gear-wide-connected',
    'fas fa-user': 'bi bi-person-fill',
    'fas fa-users': 'bi bi-people-fill',
    'fas fa-user-circle': 'bi bi-person-circle',
    'fas fa-lock': 'bi bi-lock-fill',
    'fas fa-unlock': 'bi bi-unlock-fill',
    'fas fa-key': 'bi bi-key-fill',
    'fas fa-sign-out-alt': 'bi bi-box-arrow-right',
    'fas fa-sign-in-alt': 'bi bi-box-arrow-in-right',
    'fas fa-home': 'bi bi-house-fill',
    'fas fa-chart-line': 'bi bi-graph-up',
    'fas fa-chart-bar': 'bi bi-bar-chart-fill',
    'fas fa-chart-pie': 'bi bi-pie-chart-fill',
    'fas fa-calendar': 'bi bi-calendar-fill',
    'fas fa-clock': 'bi bi-clock-fill',
    'far fa-clock': 'bi bi-clock',
    'fas fa-history': 'bi bi-clock-history',
    'fas fa-envelope': 'bi bi-envelope-fill',
    'far fa-envelope': 'bi bi-envelope',
    'fas fa-phone': 'bi bi-telephone-fill',
    'fas fa-mobile-alt': 'bi bi-phone-fill',
    'fas fa-shopping-cart': 'bi bi-cart-fill',
    'fas fa-box': 'bi bi-box-seam',
    'fas fa-boxes': 'bi bi-boxes',
    'fas fa-box-open': 'bi bi-box2',
    'fas fa-receipt': 'bi bi-receipt',
    'fas fa-qrcode': 'bi bi-qr-code',
    'fas fa-barcode': 'bi bi-upc-scan',
    'fas fa-spinner': 'bi bi-arrow-repeat',
    'fas fa-sync-alt': 'bi bi-arrow-clockwise',
    'fas fa-redo': 'bi bi-arrow-clockwise',
    'fas fa-undo': 'bi bi-arrow-counterclockwise',
    'fas fa-arrow-right': 'bi bi-arrow-right',
    'fas fa-arrow-left': 'bi bi-arrow-left',
    'fas fa-arrow-up': 'bi bi-arrow-up',
    'fas fa-arrow-down': 'bi bi-arrow-down',
    'fas fa-chevron-right': 'bi bi-chevron-right',
    'fas fa-chevron-left': 'bi bi-chevron-left',
    'fas fa-chevron-up': 'bi bi-chevron-up',
    'fas fa-chevron-down': 'bi bi-chevron-down',
    'fas fa-external-link-alt': 'bi bi-box-arrow-up-right',
    'fas fa-graduation-cap': 'bi bi-mortarboard-fill',
    'fas fa-book': 'bi bi-book-fill',
    'fas fa-clipboard': 'bi bi-clipboard-fill',
    'fas fa-clipboard-check': 'bi bi-clipboard-check-fill',
    'fas fa-list': 'bi bi-list',
    'fas fa-th': 'bi bi-grid-3x3-gap-fill',
    'fas fa-bars': 'bi bi-list',
    'fas fa-ellipsis-h': 'bi bi-three-dots',
    'fas fa-ellipsis-v': 'bi bi-three-dots-vertical',
    'fas fa-star': 'bi bi-star-fill',
    'far fa-star': 'bi bi-star',
    'fas fa-heart': 'bi bi-heart-fill',
    'far fa-heart': 'bi bi-heart',
    'fas fa-thumbs-up': 'bi bi-hand-thumbs-up-fill',
    'far fa-thumbs-up': 'bi bi-hand-thumbs-up',
    'fas fa-comment': 'bi bi-chat-fill',
    'far fa-comment': 'bi bi-chat',
    'fas fa-comments': 'bi bi-chat-dots-fill',
    'fas fa-paper-plane': 'bi bi-send-fill',
    'fas fa-share': 'bi bi-share-fill',
    'fas fa-bookmark': 'bi bi-bookmark-fill',
    'far fa-bookmark': 'bi bi-bookmark',
    'fas fa-flag': 'bi bi-flag-fill',
    'fas fa-tag': 'bi bi-tag-fill',
    'fas fa-tags': 'bi bi-tags-fill',
    'fas fa-folder': 'bi bi-folder-fill',
    'far fa-folder': 'bi bi-folder',
    'fas fa-folder-open': 'bi bi-folder2-open',
    'fas fa-file': 'bi bi-file-earmark-fill',
    'far fa-file': 'bi bi-file-earmark',
    'fas fa-file-alt': 'bi bi-file-text-fill',
    'far fa-file-alt': 'bi bi-file-text',
    'fas fa-image': 'bi bi-image-fill',
    'far fa-image': 'bi bi-image',
    'fas fa-video': 'bi bi-camera-video-fill',
    'fas fa-music': 'bi bi-music-note',
    'fas fa-volume-up': 'bi bi-volume-up-fill',
    'fas fa-volume-down': 'bi bi-volume-down-fill',
    'fas fa-volume-mute': 'bi bi-volume-mute-fill',
    'fas fa-microphone': 'bi bi-mic-fill',
    'fas fa-camera': 'bi bi-camera-fill',
    'fas fa-wifi': 'bi bi-wifi',
    'fas fa-bluetooth': 'bi bi-bluetooth',
    'fas fa-battery-full': 'bi bi-battery-full',
    'fas fa-plug': 'bi bi-plug-fill',
    'fas fa-database': 'bi bi-database-fill',
    'fas fa-server': 'bi bi-server',
    'fas fa-cloud': 'bi bi-cloud-fill',
    'fas fa-cloud-upload-alt': 'bi bi-cloud-upload-fill',
    'fas fa-cloud-download-alt': 'bi bi-cloud-download-fill',
    'fas fa-globe': 'bi bi-globe',
    'fas fa-map-marker-alt': 'bi bi-geo-alt-fill',
    'fas fa-location-arrow': 'bi bi-cursor-fill',
    'fas fa-compass': 'bi bi-compass-fill',
    'fas fa-plane': 'bi bi-airplane-fill',
    'fas fa-car': 'bi bi-car-front-fill',
    'fas fa-bus': 'bi bi-bus-front-fill',
    'fas fa-train': 'bi bi-train-front-fill',
    'fas fa-ship': 'bi bi-water',
    'fas fa-bicycle': 'bi bi-bicycle',
    'fas fa-building': 'bi bi-building-fill',
    'fas fa-hospital': 'bi bi-hospital-fill',
    'fas fa-store': 'bi bi-shop',
    'fas fa-store-alt': 'bi bi-shop-window',
    'fas fa-coffee': 'bi bi-cup-hot-fill',
    'fas fa-utensils': 'bi bi-egg-fried',
    'fas fa-pizza-slice': 'bi bi-slash-circle',
    'fas fa-hamburger': 'bi bi-list',
    'fas fa-ice-cream': 'bi bi-snow',
    'fas fa-birthday-cake': 'bi bi-cake2-fill',
    'fas fa-gift': 'bi bi-gift-fill',
    'fas fa-trophy': 'bi bi-trophy-fill',
    'fas fa-medal': 'bi bi-award-fill',
    'fas fa-crown': 'bi bi-award',
    'fas fa-gem': 'bi bi-gem',
    'fas fa-rocket': 'bi bi-rocket-takeoff-fill',
    'fas fa-fire': 'bi bi-fire',
    'fas fa-bolt': 'bi bi-lightning-fill',
    'fas fa-lightbulb': 'bi bi-lightbulb-fill',
    'far fa-lightbulb': 'bi bi-lightbulb',
    'fas fa-sun': 'bi bi-sun-fill',
    'far fa-sun': 'bi bi-sun',
    'fas fa-moon': 'bi bi-moon-fill',
    'far fa-moon': 'bi bi-moon',
    'fas fa-cloud-sun': 'bi bi-cloud-sun-fill',
    'fas fa-cloud-moon': 'bi bi-cloud-moon-fill',
    'fas fa-snowflake': 'bi bi-snow',
    'fas fa-umbrella': 'bi bi-umbrella-fill',
    'fas fa-thermometer-half': 'bi bi-thermometer-half',
    'fas fa-wind': 'bi bi-wind',
    'fas fa-water': 'bi bi-water',
    'fas fa-tree': 'bi bi-tree-fill',
    'fas fa-leaf': 'bi bi-flower1',
    'fas fa-seedling': 'bi bi-flower2',
    'fas fa-flower': 'bi bi-flower3',
    'fas fa-apple-alt': 'bi bi-apple',
    'fas fa-carrot': 'bi bi-egg',
    'fas fa-lemon': 'bi bi-circle-fill',
    'fas fa-pepper-hot': 'bi bi-fire',
    'fas fa-drumstick-bite': 'bi bi-egg-fried',
    'fas fa-bacon': 'bi bi-dash-lg',
    'fas fa-hotdog': 'bi bi-dash-lg',
    'fas fa-cookie': 'bi bi-circle',
    'fas fa-candy-cane': 'bi bi-candy',
    'fas fa-glass-cheers': 'bi bi-cup-straw',
    'fas fa-wine-glass': 'bi bi-cup',
    'fas fa-beer': 'bi bi-cup-fill',
    'fas fa-mug-hot': 'bi bi-cup-hot-fill',
    'fas fa-archive': 'bi bi-archive-fill',
    'fas fa-ban': 'bi bi-slash-circle-fill',
    'fas fa-shield-alt': 'bi bi-shield-fill-check',
    'fas fa-exclamation-circle': 'bi bi-exclamation-circle-fill',
    'fas fa-question-circle': 'bi bi-question-circle-fill',
    'fas fa-hourglass-half': 'bi bi-hourglass-split',
    'fas fa-inbox': 'bi bi-inbox-fill',
    'fas fa-plus-circle': 'bi bi-plus-circle-fill',
    'fas fa-check-double': 'bi bi-check2-all',
    'fas fa-award': 'bi bi-award-fill'
};

// Color mapping from old to new palette
const colorMapping = {
    // Blues (old blue-900 to new primary colors)
    'blue-900': 'primary-900',
    'blue-800': 'primary-800',
    'blue-700': 'primary-700',
    'blue-600': 'accent-600',
    'blue-500': 'accent-500',
    'blue-400': 'accent-400',
    
    // Oranges to warning colors
    'orange-600': 'warning-600',
    'orange-500': 'warning-500',
    'orange-400': 'warning-400',
    
    // Greens to success colors
    'green-600': 'success-600',
    'green-500': 'success-500',
    'green-400': 'success-400',
    
    // Reds to danger colors
    'red-600': 'danger-600',
    'red-500': 'danger-500',
    'red-400': 'danger-400',
    
    // Grays to neutral colors
    'gray-50': 'gray-50',
    'gray-100': 'gray-100',
    'gray-200': 'gray-200',
    'gray-300': 'gray-300',
    'gray-400': 'gray-400'
};

// Export for use in Node.js or browser
if (typeof module !== 'undefined' && module.exports) {
    module.exports = { iconMapping, colorMapping };
} else {
    window.iconMapping = iconMapping;
    window.colorMapping = colorMapping;
}

console.log('UI/UX Update mappings loaded');
console.log(`Total icon mappings: ${Object.keys(iconMapping).length}`);
console.log(`Total color mappings: ${Object.keys(colorMapping).length}`);
